import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Ilmi Faizan Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-6 md:px-20 lg:px-40 dark:bg-gray-900 transition">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-white">
              Web Developer
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl dark:text-white"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Ilmi Faizan
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-slate-300">
              Frontend and Backend Web Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-slate-400">
              Freelancer providing services for programming and design content
              needs. Join me down below and let's get cracking!
            </p>
          </div>
          <div className="text-4xl md:text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillTwitterCircle className="cursor-pointer" />
            <AiFillLinkedin className="cursor-pointer" />
            <AiFillYoutube className="cursor-pointer" />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={deved} layout="fill" objectFit="cover" alt="Image" />
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl pb-1 pt-10 dark:text-slate-300">
              Services I offer
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-slate-400">
              Since the beginning of my journey as a freel developer, I've done
              remote work for
              <span className="text-teal-500"> agencies </span> consulted for{" "}
              <span className="text-teal-500">startups </span>and collaborated
              with talented people to create digital products for both business
              and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-slate-400">
              I offer from a wide range of services, including programming and
              teaching.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 transition ease-in dark:bg-slate-300">
              <Image
                src={design}
                width={100}
                height={100}
                className="mx-auto"
                alt="Image"
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Design
              </h3>
              <p className="py-2">
                Creating elegant design suited for your needs following design
                theory.
              </p>
              <h4 className="py-4 text-teal-600 font-medium">
                Design tools I use
              </h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-slate-300">
              <Image
                src={consulting}
                width={100}
                height={100}
                className="mx-auto"
                alt="Image"
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Design
              </h3>
              <p className="py-2">
                Creating elegant design suited for your needs following design
                theory.
              </p>
              <h4 className="py-4 text-teal-600 font-medium">
                Design tools I use
              </h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-slate-300">
              <Image
                src={code}
                width={100}
                height={100}
                className="mx-auto"
                alt="Image"
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Design
              </h3>
              <p className="py-2">
                Creating elegant design suited for your needs following design
                theory.
              </p>
              <h4 className="py-4 text-teal-600 font-medium">
                Design tools I use
              </h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl pb-1 pt-10 dark:text-slate-300">
              Portfolio
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-slate-400">
              Since the beginning of my journey as a freel developer, I've done
              remote work for
              <span className="text-teal-500"> agencies </span> consulted for{" "}
              <span className="text-teal-500">startups </span>and collaborated
              with talented people to create digital products for both business
              and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-slate-400">
              I offer from a wide range of services, including programming and
              teaching.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 relative group border-red-100">
              <Image
                src={web1}
                alt="Image"
                className="rounded-lg object-cover shadow-lg group-hover:brightness-50 transition ease-in"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
              <p className="absolute text-lg opacity-0 transition top-1/2 -translate-y-1/2 left-1/2 -translate-x-1/2 text-slate-100 font-medium group-hover:opacity-100 md:text-2xl">
                Project I
              </p>
            </div>
            <div className="basis-1/3 flex-1 relative group border-red-100">
              <Image
                src={web2}
                alt="Image"
                className="rounded-lg object-cover shadow-lg group-hover:brightness-50 transition ease-in"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
              <p className="absolute text-lg opacity-0 transition top-1/2 -translate-y-1/2 left-1/2 -translate-x-1/2 text-slate-100 font-medium group-hover:opacity-100 md:text-2xl">
                Project II
              </p>
            </div>
            <div className="basis-1/3 flex-1 relative group border-red-100">
              <Image
                src={web3}
                alt="Image"
                className="rounded-lg object-cover shadow-lg group-hover:brightness-50 transition ease-in"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
              <p className="absolute text-lg opacity-0 transition top-1/2 -translate-y-1/2 left-1/2 -translate-x-1/2 text-slate-100 font-medium group-hover:opacity-100 md:text-2xl">
                Project III
              </p>
            </div>
            <div className="basis-1/3 flex-1 relative group border-red-100">
              <Image
                src={web4}
                alt="Image"
                className="rounded-lg object-cover shadow-lg group-hover:brightness-50 transition ease-in"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
              <p className="absolute text-lg opacity-0 transition top-1/2 -translate-y-1/2 left-1/2 -translate-x-1/2 text-slate-100 font-medium group-hover:opacity-100 md:text-2xl">
                Project IV
              </p>
            </div>
            <div className="basis-1/3 flex-1 relative group border-red-100">
              <Image
                src={web5}
                alt="Image"
                className="rounded-lg object-cover shadow-lg group-hover:brightness-50 transition ease-in"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
              <p className="absolute text-lg opacity-0 transition top-1/2 -translate-y-1/2 left-1/2 -translate-x-1/2 text-slate-100 font-medium group-hover:opacity-100 md:text-2xl">
                Project V
              </p>
            </div>
            <div className="basis-1/3 flex-1 relative group border-red-100">
              <Image
                src={web6}
                alt="Image"
                className="rounded-lg object-cover shadow-lg group-hover:brightness-50 transition ease-in"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
              <p className="absolute text-lg opacity-0 transition top-1/2 -translate-y-1/2 left-1/2 -translate-x-1/2 text-slate-100 font-medium group-hover:opacity-100 md:text-2xl">
                Project VI
              </p>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
